#:import datetime datetime.datetime
#:import LowerScrollEffect components.effects.LowerScrollEffect
#:import ScrollEffect kivy.effects.scroll.ScrollEffect
#:import StretchOverScrollStencil components.effects.StretchOverScrollStencil
#:import SharedAxisTransition components.transition.SharedAxisTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import ToggleButtonBehavior  kivy.uix.behaviors.togglebutton.ToggleButtonBehavior
#:import gcfh kivy.utils.get_color_from_hex
#:import Window kivy.core.window.Window
#:import shorten_text libs.shorten_text
#:set primary_color "#2962ff"
#:set icon_path "assets/fonts/materialdesignicons-webfont.ttf"

<TouchRippleBehavior>:
    ripple_duration_in: 0
    ripple_duration_out: 0
    ripple_color: app.theme_cls.transparent_color

<StencilBoxLayout@CustomBoxLayout+StencilBehavior>

<ButtonBoxLayout@TouchRippleButtonBehavior+CustomBoxLayout+AdaptiveBehavior>
<ToggleBoxLayout@ToggleButtonBehavior+CustomBoxLayout>
    allow_no_selection: False
    line_color: app.theme_cls.primary_color if self.active else app.theme_cls.transparent_color

<Chip@ButtonBoxLayout>
    size_hint_y: None
    height: "32dp"
    bg_color: app.theme_cls.bg_color
    line_width: 1
    radius: "6dp"
    text: ""
    adaptive_width: True
    CustomLabel:
        text: root.text
        adaptive_width: True
        halign: "center"
        bold: True
        padding: "15dp", 0
        pos_hint: {"center_y": .5}
        font_size: "14dp"

<MagicButton@CustomButton+MagicBehavior>

<TagTextInput@CustomBoxLayout>:
    adaptive_height: True
    orientation: "vertical"
    spacing: "5dp"
    tag: ""
    hint_text: ""
    text: ""
    password: False
    bold: False
    input_type: "null"
    input_filter: None
    focus: False
    font_size: "15sp"
    txt_input_bg_color: app.theme_cls.card_color
    txt_input_padding: "15dp", "18dp"
    keyboard_show_callback: lambda: None
    keyboard_hide_callback: lambda: None
    CustomLabel:
        text: root.tag
        adaptive_height: True
        markup: True
        font_size: "13sp"
        color: app.theme_cls.text_color[:3] + [.7]
    CustomTextInput:
        id: txt_input
        padding: root.txt_input_padding
        radius: "10dp"
        password: root.password
        text: root.text
        bg_color: root.txt_input_bg_color
        focus: root.focus
        font_size: root.font_size
        hint_text: root.hint_text
        input_type: root.input_type
        input_filter: root.input_filter
        on_text: root.text = self.text
        on_focus: root.focus = self.focus
        on_keyboard_show: root.keyboard_show_callback()
        on_keyboard_hide: root.keyboard_hide_callback()

<Selector>
    color: app.theme_cls.primary_color

<ScreenManager>
    canvas.before:
        Clear
    canvas.after:
        Clear

<PurchasedSheet>
    -padding: "20dp", "40dp", "20dp", app.navbar_height + dp(40)
    spacing: "20dp"
    Icon:
        icon: "check"
        font_size: "50sp"
        pos_hint: {"center_x": .5}
        color: app.theme_cls.primary_color
    CustomLabel:
        adaptive_height: True
        text: "Congratulations"
        bold: True
        font_size: "32sp"
        halign: "center"
    CustomLabel:
        adaptive_height: True
        text: "You have successfully unlocked your signature style and your coins have been added to your account. "
        color: app.theme_cls.text_color[:3] + [.7]
        halign: "center"

<MoodOccasionButton@ToggleButtonBehavior+CustomLabel>:
    adaptive_size: True
    padding: "7dp", "5dp"
    pos_hint: {"center_x": .5}
    radius: "7dp"
    font_size: "11sp"
    color: app.theme_cls.bg_color if self.active else app.theme_cls.text_color
    bold: True
    bg_color: app.theme_cls.primary_color if self.active else app.theme_cls.bg_color
    shadow_color: app.theme_cls.shadow_color
    line_color: app.theme_cls.text_color[:3] + [.3]
    spread_radius: -dp(3), -dp(3)

<DisconnectSheet>
    CustomBoxLayout:
        adaptive_height: True
        spacing: "10dp"
        CustomLabel:
            adaptive_height: True
            text: root.text
            halign: "center"
            font_size: "16sp"
            pos_hint: {"center_y": .5}
            markup: True
            on_ref_press: root.dispatch("on_ref_press")
        IconButton:
            icon: root.icon
            bg_color: app.theme_cls.accent_color
            radius: "10dp"
            pos_hint: {"top": 1}