<CoinScreen>
    name: "coin screen"
    BoxLayout:
        orientation: "vertical"
        CustomBoxLayout:
            adaptive_height: True
            padding: "20dp", "10dp"
            IconButton:
                icon: "arrow-left"
                radius: self.height / 2
                bg_color: app.theme_cls.card_color
                pos_hint: {"center_y": .5}
                size: "35dp", "35dp"
                font_size: "20sp"
                shadow_color: app.theme_cls.shadow_color
                on_release: root.manager.current = "home screen"
            CustomLabel:
                text: "Earn Rewards"
                adaptive_height: True
                bold: True
                halign: "center"
                pos_hint: {"center_y": .5}
            ButtonBoxLayout:
                adaptive_size: True
                shadow_color: app.theme_cls.shadow_color
                bg_color: app.theme_cls.card_color
                radius: self.height / 2
                padding: "10dp", "5dp"
                spacing: "5dp"
                pos_hint: {"center_y": .5}
                on_release: root.manager.current = "coin screen"
                Icon:
                    icon: "star-circle"
                    font_size: "20sp"
                CustomLabel:
                    text: "{}".format(app.coins)
                    bold: True
                    pos_hint: {"center_y": .5}
                    adaptive_size: True
                    font_size: "14sp"
        ScrollView:
            id: sv
            scroll_distance: 0
            bar_width: 0
            do_scroll_x: False
            effect_cls: "ScrollEffect"
            CustomBoxLayout:
                adaptive_height: True
                padding: "20dp", "10dp"
                orientation: "vertical"
                spacing: "20dp"
                CustomBoxLayout:
                    adaptive_height: True
                    padding: "20dp", "20dp", "20dp", "10dp"
                    radius: "16dp"
                    bg_color: app.theme_cls.primary_color[:3] + [.1]
                    line_color: app.theme_cls.text_color[:3] + [.8]
                    spacing: "10dp"
                    orientation: "vertical"
                    CustomBoxLayout:
                        adaptive_height: True
                        spacing: "20dp"
                        Icon:
                            icon: "star-circle"
                            font_size: "32sp"
                            pos_hint: {"top": 1}
                        CustomLabel:
                            text: "Earn free image generations by completing simple tasks!"
                            font_size: "16sp"
                            adaptive_height: True
                    CustomBoxLayout:
                        adaptive_size: True
                        padding: "20dp"
                        pos_hint: {"center_x": .5}
                        CustomLabel:
                            text: "Balance: "
                            adaptive_size: True
                        CustomLabel:
                            id: balance
                            coins: 0
                            text: "{} bonus coin".format(self.coins)
                            adaptive_size: True
                            bold: True
                            color: app.theme_cls.primary_color
                ButtonBoxLayout:
                    shadow_color: app.theme_cls.shadow_color
                    radius: "16dp"
                    line_color: app.theme_cls.text_color[:3] + [.3]
                    bg_color: app.theme_cls.card_color
                    adaptive_height: True
                    padding: "20dp"
                    spacing: "10dp"
                    on_release: root.show_ads()
                    Icon:
                        icon: "play-circle"
                        font_size: "40sp"
                        pos_hint: {"center_y": .5}
                    CustomBoxLayout:
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                        spacing: "10dp"
                        CustomLabel:
                            text: "Watch Video Ads"
                            font_size: "16sp"
                            bold: True
                            adaptive_height: True
                            pos_hint: {"center_y": .5}
                        CustomLabel:
                            adaptive_height: True
                            text: "Watch video ads to earn bonus coins rewards!"
                            font_size: "14sp"
                            pos_hint: {"center_y": .5}
                CustomBoxLayout:
                    id: inapp
                    adaptive_height: True
                    spacing: "15dp"
                    orientation: "vertical"
        CustomBoxLayout:
            id: bottom
            adaptive_height: True
            padding: "20dp"
            orientation: "vertical"
            spacing: "10dp"
            CustomButton:
                id: btn
                size_hint_y: None
                height: "45dp"
                font_size: "16sp"
                radius: self.height / 2
                amount: 0
                currency: ""
                text: "Continue {:,.2f} {}".format(self.amount, self.currency)
                markup: True
                pos_hint: {"center_x": .5}
                markup: True
                bold: True
                on_release: root.launch_billing_flow()
            CustomLabel:
                text: "Terms and Conditions Apply"
                adaptive_height: True
                font_size: "10sp"
                halign: "center"






