from kivy.factory import Factory


def register_factory():
    r = Factory.register
    r("CoverImage", module="components.image")
    r("CustomLabel", module="components.label")
    r("RealRecycleView", module="components.scrollview")
    r("Divider", module="components.divider")
    r("Icon", module="components.label")
    r("IconButton", module="components.button")
    r("BackgroundColorBehavior", module="components.behaviors")
    r("AdaptiveBehavior", module="components.behaviors")
    r("StencilBehavior", module="components.behaviors")
    r("CustomToggleButtonBehavior", module="components.behaviors")
    r("CustomButton", module="components.button")
    r("CustomToggleButton", module="components.button")
    r("CustomCheckBox", module="components.checkbox")
    r("DialogScrim", module="components.scrim")
    r("CustomTextInput", module="components.textinput")
    r("CircularProgressIndicator", module="components.progressindicator")
    r("LinearProgressIndicator", module="components.progressindicator")
    r("BaseSheet", module="components.sheet")
    r("OtpSheet", module="components.sheet")
    r("ChatList", module="components.list")
    r("TabsCarousel", module="components.tab")
    r("CustomBoxLayout", module="components.layout")
    r("DotSpinner", module="components.spinner")
    r("CustomCarousel", module="components.layout")
    r("BarChart", module="components.charts")
    r("PieChart", module="components.charts")
    r("RadarChart", module="components.charts")
    r("Graph", module="components.graph")
    r("SmoothLinePlot", module="components.graph")
    r("Gradient", module="components.gradient")
    r("MagicBehavior", module="components.behaviors")
    r("BackdropBehavior", module="components.behaviors")
    r("FrostedGlass", module="kivy_garden.frostedglass")
    r("LowerScrollEffect", module="components.effects")
    r("HardStopScrollEffect", module="components.effects")
    r("LowerDampedScrollEffect", module="components.effects")
    r("HardStopDampedScrollEffect", module="components.effects")
    r("StretchOverScrollStencil", module="components.effects")
    r("RealRecycleView", module="components.recycler")
